### PR TITLE
Fixed example in README.md to match expected service name

### PR DESCRIPTION
**Pull request by Bucknalla**
Change-type: patch
Signed-off-by: Alex Bucknall <alexbucknall@balena.io>

### CODE REVIEW

**Review by phil-d-wilson — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Stealthily adding patch changes to already approved PR's and getting them merged. That's what I call omni-win. 
Saw this PR not merged, saw the change it was making and it was needed. I thought I add my change in it too and get it merged.

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Comment by phil-d-wilson** [comment]
@balena-ci retest

**Comment by phil-d-wilson** [comment]
@balena-ci retest

**Pull request merged**
